name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_PAT }}
      - name: connect to github container registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image
        run: sudo docker pull ghcr.io/imadfaouzi/demo-app-gitactions:latest

      - name: Remove old container
        run: sudo docker rm -f demo-app-gitactions-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 80:3000 --name demo-app-gitactions-container ghcr.io/imadfaouzi/demo-app-gitactions:latest
